baseURL = "http://sigmaone.netlify.app"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring-light"
title = "SIGMA"
[markup.goldmark.renderer]
unsafe = true
